version: 1
formatters:
  simple:
    format: '%(asctime)s - %(filename)s:%(lineno)s - %(funcName)20s() - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: ERROR
    formatter: simple
    stream: ext://sys.stdout
loggers:
  sampleLogger:
    level: ERROR
    handlers: [console]
    propagate: no
root:
  level: ERROR
  handlers: [console]